#!/bin/bash

rm -rf /var/www/osticket/upload/setup

echo "[osticket]" >> /etc/rsyncd.conf
echo "path = /var/www/osticket" >> /etc/rsyncd.conf
systemctl start rsyncd

a=$(ip ad show dev eth1 | grep 'inet ' | awk '{print $2;}' | awk -F / '{print $1;}')

if [[ "$a" == "192.168.70.21" ]]; then
    rsync -au rsync://192.168.70.22/osticket/upload/include/ost-config.php /var/www/osticket/upload/include/ost-config.php
fi

if [[ "$a" == "192.168.70.22" ]]; then
    rsync -au rsync://192.168.70.21/osticket/upload/include/ost-config.php /var/www/osticket/upload/include/ost-config.php
fi

exit
