---
- name: enable and start ntp
  service: name=ntpd
           enabled=yes
           state=started

- name: configure haproxy
  shell: cp /vagrant/haproxy.cfg /etc/haproxy/haproxy.cfg

- name: enable and start haproxy
  service: name=haproxy
           enabled=yes
           state=started

- name: Disable SELinux
  shell: setenforce 0

